version: "3.8"
services:
  marketdb:
    build:
      context: ./database
    image: vupham0402/marketdb
    container_name: marketdb
    ports:
      - "3306:3306"
    volumes: 
      - marketdbdata: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root