version: "3.8"
services:
  marketexpress:
    build:
      context: ./frontend
    image: vupham0402/marketexpress
    container_name: marketexpress
    ports: 
      - "5000:5000"

  marketreact:
    build:
      context: ./frontend/client
    image: vupham0402/marketreact
    container_name: marketreact
    ports:
      - "3000:3000"

  marketnginx:
    build:
      context: ./nginx
    image: vupham0402/marketnginx
    container_name: marketnginx
    ports:
      - "80:80"
  
  marketdjango:
    build:
      context: ./backend
    image: vupham0402/marketdjango
    container_name: marketdjango
    ports:
      - "8000:8000"
    depends_on:
      - marketdb

  marketdb:
    build:
      context: ./database
    image: vupham0402/marketdb
    container_name: marketdb
    ports:
      - "3306:3306"
    volumes: 
      - marketdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
    marketdbdata: {}