# Generated by Django 4.1.7 on 2023-09-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditNotification',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('productid', models.CharField(db_column='ProductID', max_length=255)),
                ('vendor', models.CharField(db_column='Vendor', max_length=255)),
                ('sku', models.CharField(db_column='SKU', max_length=45)),
                ('description', models.TextField(db_column='Description')),
                ('uom', models.CharField(db_column='UoM', max_length=45)),
                ('qty', models.IntegerField(db_column='Qty')),
                ('tier1', models.CharField(db_column='Tier1', max_length=45)),
                ('tier2', models.CharField(db_column='Tier2', max_length=45)),
                ('tier3', models.CharField(db_column='Tier3', max_length=45)),
                ('tier4', models.CharField(db_column='Tier4', max_length=45)),
                ('active', models.IntegerField(db_column='Active')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('note', models.TextField(db_column='Note')),
            ],
            options={
                'db_table': 'edit_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entity_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'entities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('catalognumber', models.CharField(blank=True, db_column='CatalogNumber', max_length=45, null=True)),
                ('eachqty', models.IntegerField(db_column='EachQty')),
                ('totalcost', models.DecimalField(db_column='TotalCost', decimal_places=2, max_digits=15)),
                ('vendor', models.CharField(db_column='Vendor', max_length=50)),
                ('price_per', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exact_match', models.IntegerField(blank=True, null=True)),
                ('db_sku', models.CharField(max_length=45)),
                ('db_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'member_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumgenSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'numGen_seq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('manuf_prod_num', models.CharField(max_length=45)),
                ('description', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=255)),
                ('unspsc', models.CharField(blank=True, max_length=45, null=True)),
                ('katena_mfr', models.CharField(blank=True, max_length=11, null=True)),
                ('gtn_upc', models.BigIntegerField(blank=True, null=True)),
                ('family', models.CharField(blank=True, max_length=45, null=True)),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsHasVendors',
            fields=[
                ('product_has_vendor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=45)),
                ('uom', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=11, null=True)),
                ('units_in_uom', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products_has_vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('subcategory_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'subcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('tier_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('tier_name', models.CharField(max_length=11, unique=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('member_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dba_applicable', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_input',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketBasketCLN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cln', models.CharField(max_length=45)),
                ('vendor_cln', models.CharField(max_length=45)),
                ('sku_cln', models.CharField(max_length=45)),
                ('invoice_number_cln', models.CharField(max_length=45)),
                ('description_cln', models.CharField(max_length=300)),
                ('quantity_cln', models.CharField(max_length=45)),
                ('price_cln', models.CharField(max_length=45)),
                ('total_cln', models.CharField(max_length=45)),
                ('index_src', models.IntegerField()),
            ],
            options={
                'db_table': 'market_basket_cln',
            },
        ),
        migrations.CreateModel(
            name='MarketBasketFIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fin', models.DateTimeField()),
                ('vendor_fin', models.CharField(max_length=45)),
                ('sku_fin', models.CharField(max_length=45)),
                ('invoice_number_fin', models.IntegerField()),
                ('description_fin', models.CharField(max_length=300)),
                ('quantity_fin', models.IntegerField()),
                ('price_fin', models.IntegerField()),
                ('total_fin', models.IntegerField()),
                ('index_src', models.IntegerField()),
            ],
            options={
                'db_table': 'market_basket_fin',
            },
        ),
        migrations.CreateModel(
            name='MarketBasketSRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_src', models.DateTimeField()),
                ('vendor_src', models.CharField(max_length=45)),
                ('sku_src', models.CharField(max_length=45)),
                ('invoice_number_src', models.IntegerField()),
                ('description_src', models.CharField(max_length=300)),
                ('quantity_src', models.IntegerField()),
                ('price_src', models.IntegerField()),
                ('total_src', models.IntegerField()),
                ('index_src', models.IntegerField()),
            ],
            options={
                'db_table': 'market_basket_src',
            },
        ),
        migrations.CreateModel(
            name='MarketBasketTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('vendor_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('sku_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('invoice_number_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('description_cln', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('price_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('total_cln', models.CharField(blank=True, max_length=45, null=True)),
                ('issue_cln', models.IntegerField(blank=True, null=True)),
                ('error_column', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'market_basket_tmp',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.entities')),
                ('peg', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceArchive',
            fields=[
                ('price_archive', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.productshasvendors')),
                ('pa_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'price_archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.entities')),
                ('tier_description', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=255, null=True)),
                ('vendor_img', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembersHasVendors',
            fields=[
                ('members_member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.members')),
                ('eyepro_tier', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'members_has_vendors',
                'managed': False,
            },
        ),
    ]
